export const JOBS_LIST_REQUEST = 'JOBS_LIST_REQUEST';
export const JOBS_LIST_SUCCESS = 'JOBS_LIST_SUCCESS';
export const JOBS_LIST_FAIL = 'JOBS_LIST_FAIL';
export const SET_QUERIES = 'SET_QUERIES';
export const GET_POSTULANTS_REQUEST = 'GET_POSTULANTS_REQUEST';
export const GET_POSTULANTS_SUCCESS = 'GET_POSTULANTS_SUCCESS';
export const GET_POSTULANTS_FAIL = 'GET_POSTULANTS_FAIL';
