export const POSTULATION_REQUEST = 'POSTULATION_REQUEST';
export const POSTULATION_SUCCESS = 'POSTULATION_SUCCESS';
export const POSTULATION_FAIL = 'POSTULATION_FAIL';
export const POSTULATION_INFO = 'POSTULATION_INFO';
export const POSTULATION_INFO_FAIL = 'POSTULATION_INFO_FAIL';
