export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const GET_USER_INFO = 'GET_USER_INFO';
export const SIGN_OUT = 'SIGN_OUT';
export const USER_INFO_VALIDATION = 'USER_INFO_VALIDATION';
